#!/bin/bash
# Function to get DNS information

info() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]; then
    info "$2.$1" "$2"
    exit 0
fi

info "www.$1" "www"
info "lb-01.$1" "lb-01"
info "web-01.$1" "web-01"
info "web-02.$1" "web-02"
