#!/usr/bin/env bash
# Transfer a file to your server
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit 1;
fi
path_file=$1;
ip=$2;
username=$3;
path_ssh=$4;
scp -i "$path_ssh" -o StrictHostKeyChecking=no "$path_file" "$username@$ip:~/";
