#!/usr/bin/env bash
# resetarting Nginx server
sudo apt-get -y update
sudo apt-get install -y nginx
# sudo ufw allow "Nginx HTTP"
sudo service nginx start
# sudo chown -R "$USER":"$USER" /var/www/html
# sudo chmod -R 755 /var/www/

# Create a custom index.html
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
