#!/usr/bin/env bash
# resetarting apaches server
apt-get -y update
apt-get install -y nginx

# Create a custom index.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
