#!/usr/bin/env bash
# resetarting apaches server
apt-get -y update
apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
# Create a custom index.html
echo "Hello World!" > /var/www/html/.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
