#!/usr/bin/env bash
# resetarting apaches server
apt-get -y update
apt-get install -y nginx

# Create a custom index.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Write the new Nginx configuration using tee
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://github.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx start
