#!/usr/bin/env bash
# 0. Double the number of webservers 
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple "Hello World!" page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Write the new Nginx configuration using tee
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Check Nginx configuration for syntax errors
if sudo nginx -t; then
    sudo systemctl restart nginx
else
    echo "Nginx configuration is invalid."
fi
