#!/usr/bin/env bash
# 0. Double the number of webservers 
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple "Hello World!" page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Write the new Nginx configuration using tee
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.nginx-debian.html index.nginx-debian.htm;

    location /redirect_me {
        return 301 http://github.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

# Check Nginx configuration for syntax errors
sudo service nginx restart
