#!/usr/bin/env bash
# a Bash script that: 
#    Creates the file "/var/run/myscript.pid" containing its PID
#    Displays "To infinity and beyond" indefinitely
#    Displays "I hate the kill command" when receiving a SIGTERM signal
#    Displays "Y U no love me?!"" when receiving a SIGINT signal
#    Deletes the file "/var/run/myscript.pid" and terminates itself
#    when receiving a SIGQUIT or SIGTERM signal
echo "$$" > /var/run/myscript.pid
termcmd()
{
    rm /var/run/myscript.pid
    exit
}

i=1
while [ $i -le 2 ];do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && termcmd' SIGTERM 
    trap 'termcmd' SIGQUITgit  

    
done
