#!/usr/bin/env bash
# rograms that are detached from the terminal and running in the background are called daemons
pid=$$
case $1 in
    "start")
    ./manage_my_process &
    echo $pid >  /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
    "stop")

    pkill -f "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
    "restart")
    pkill -f "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $pid >  /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
    *)
    echo "Usage: manage_my_process {start|stop|restart}"
esac
