#!/usr/bin/env bash
: ' 
Bash script that displays the time for 12 hours and 59 minutes:

    display hours from 0 to 12
    display minutes from 1 to 59
'
hour=0
min=60
while [ $hour -le 12 ];do
	if [ "$min" -eq 60 ];then
		echo "Hour: $hour"
		min=0
		((hour++))
	else 
		echo $min
	fi
	((min++))
done

