#!/usr/bin/env bash
# running as nginx user, listening on 8080
chmod 644 /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sed -i -e 's/listen 80 default_server;/listen 8080 default_server;/g' -e 's/listen \[::\]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/g' /etc/nginx/sites-available/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
