#!/usr/bin/env bash
# fix the previous task is fix shorter
chmod 644 /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
